options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/togforsinkelse-collector:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/togforsinkelse-collector:latest']
  
  # Run database migrations
  - name: 'gcr.io/$PROJECT_ID/togforsinkelse-collector:latest'
    entrypoint: 'python'
    args: ['run_migrations.py']
    env:
    - 'CLOUD_SQL_CONNECTION_NAME=toginnsikt:europe-north1:togforsinkelse-db'
    - 'GOOGLE_CLOUD_PROJECT=toginnsikt'
    - 'DB_NAME=togforsinkelse_enhanced'
    - 'DB_USER=togforsinkelse-user'
    - 'DB_PASSWORD=fPl21YN#cF0RngM9'
    - 'DB_HOST=127.0.0.1'
    - 'DB_PORT=5432'
    - 'ENTUR_API_URL=https://api.entur.io/journeyplanner/2.0/index/graphql'
    - 'CLIENT_NAME=toginnsikt-collector'
    - 'DATA_RETENTION_HOURS=48'
    - 'RETRY_DELAY_MINUTES=5'
    - 'LOG_FILE=enhanced_collector.log'
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'togforsinkelse-collector'
    - '--image'
    - 'gcr.io/$PROJECT_ID/togforsinkelse-collector:latest'
    - '--region'
    - 'europe-north1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '1'
    - '--timeout'
    - '300'
    - '--add-cloudsql-instances'
    - 'toginnsikt:europe-north1:togforsinkelse-db'
    - '--set-env-vars'
    - 'CLOUD_SQL_CONNECTION_NAME=toginnsikt:europe-north1:togforsinkelse-db,GOOGLE_CLOUD_PROJECT=toginnsikt'
    - '--service-account'
    - '383318038289-compute@developer.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/togforsinkelse-collector:latest'
